### ISSUE TITLE
Missing files in 0.12.0 release (ImportError: cannot import name schema_pb2)

### ISSUE THREAD

**Issue by wileeam** [tensorflow/metadata#8]
I believe there has been some issue with the packaging because I am getting this error when running a pipeline with tf.Transform and getting the following error that after some investigation led me to tensorflow-metadata

> File "/usr/local/lib/python2.7/dist-packages/tensorflow_transform/__init__.py", line 21, in <module>
    from tensorflow_transform.mappers import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_transform/mappers.py", line 62, in <module>
    from tensorflow_transform import schema_inference
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_transform/schema_inference.py", line 30, in <module>
    from tensorflow_transform.tf_metadata import dataset_schema
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_transform/tf_metadata/dataset_schema.py", line 23, in <module>
    from tensorflow_transform.tf_metadata import schema_utils
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_transform/tf_metadata/schema_utils.py", line 28, in <module>
    from tensorflow_metadata.proto.v0 import schema_pb2
ImportError: cannot import name schema_pb2

I checked the files at https://pypi.org/project/tensorflow-metadata/#files and they are indeed missing protos that should be there as per the aforementioned `ImportError`

**Comment by paulgc** [comment]
There seems to be a packaging issue in the latest version. Can you pin the tensorflow-metadata version to be 0.9.0 for now? We will do a minor release to fix this.

**Comment by wileeam** [comment]
Yes, pinning to the previous version solves the problem for now until the current package is pulled and/or fixed.

**Comment by paulgc** [comment]
A new version of tensorflow-metadata (0.12.1) with the fix has been released.

**Comment by brianmartin** [comment]
Hey @paulgc, appreciate the quick fix.

It looks like `0.12.1` release missed a few things though. There is no release tag and also the `__version__` in `setup.py` is still `0.12.0`. https://github.com/tensorflow/metadata/blob/42939154a6ef763c9a41fed48abea758df7c0d6a/setup.py#L20

**Comment by paulgc** [comment]
@mzinkevi @solma

**Comment by cweill** [comment]
It appears that this is still a problem with `v0.22.2`. 

```sh
>>> from tensorflow_metadata.proto.v0 import schema_pb2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'schema_pb2' from 'tensorflow_metadata.proto.v0' (~/github/tensorflow/metadata/tensorflow_metadata/proto/v0/__init__.py)
```

**Comment by odidev** [comment]
This issue seems still reproducible on x86_64 and arm64 both platforms while testing with the "pytest" command. Please share if you have any plan to fix this in some upcoming releases.
